# Generated by Django 3.2.8 on 2021-10-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=165)),
                ('Key', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
