# Generated by Django 3.2.8 on 2021-10-29 15:39

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20211027_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='msgserver',
            name='id',
        ),
        migrations.AlterField(
            model_name='msgserver',
            name='Key',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[hello.models.validate_key_range]),
        ),
    ]
